const routes = (handler)=>[
    {
        method:'POST',
        handler:handler.postPlaylistHandler,
        path:'/playlist',
        options:{
            auth:'playlist_jwt'
        }
    },
    {
        method:'GET',
        handler:handler.getPlaylistHandler,
        path:'/playlist',
        options:{
            auth:'playlist_jwt'
        }
    },
    {
        method:'DELETE',
        handler:handler.deletePlaylistHandler,
        path:'/playlist/{id}',
        options:{
            auth:'playlist_jwt'
        }
    },
    {
        method:'POST',
        handler:handler.postPlaylistAndSongHandler,
        path:'/playlist/{id}/songs',
        options:{
            auth:'playlist_jwt'
        }
    },
    {
        method:'GET',
        handler:handler.getPlaylistAndSongHandler,
        path:'/playlist/{id}/songs',
        options:{
            auth:'playlist_jwt'
        }
    },
    {
        method:'DELETE',
        handler:handler.deletePlaylistAndSongHandler,
        path:'/playlist/{id}/songs',
        options:{
            auth:'playlist_jwt'
        }
    }
]

module.exports = routes